### ISSUE TITLE
Date format malfunction in server mode

### ISSUE THREAD

**Issue by qasamppa** [inluxc/playwright-xray#22]
<img width="873" alt="Näyttökuva 2023-1-2 kello 14 06 13" src="https://user-images.githubusercontent.com/113007463/210229242-960b39a7-8ec8-46d5-a602-7c76505607a7.png">

Date format is incorrect.

**Comment by qasamppa** [comment]
OS is macOS Ventura 13.1

**Comment by inluxc** [comment]
@qasamppa sorry for the delay, no time lately, busy checking it out.

**Comment by inluxc** [comment]
@qasamppa ok, i found a bug on the code, but i can't replicate the 120 instead of the 12.
What is you timezone?
