### ISSUE TITLE
"project" key and value are dropped in server mode

### ISSUE THREAD

**Issue by qasamppa** [inluxc/playwright-xray#31]
Configuration is correct in playwright.config.ts and "projectKey" attribute has been configured they're OK. But when trying to import results to Xray, extension may drop this "project" key and value and import fails.

Error is:
`Data: { error: 'Error assembling issue data: project is required' }`

![Näyttökuva 2023-2-21 kello 8 13 48](https://user-images.githubusercontent.com/113007463/220263053-4c1a4a4b-b07e-4aeb-a13b-2a9e4b265b31.png)

**Comment by qasamppa** [comment]
I am using playwright-xray extension version 0.4.1.

**Comment by inluxc** [comment]
@rodrigoodhin Can you confirm this? i don't have serve jira

**Comment by inluxc** [comment]
Hi @qasamppa, do you still have the issue? If not i will close the issue.

**Comment by qasamppa** [comment]
You can close the issue. We gave up for now with this, so if it's working for others, I am happy.

**Comment by inluxc** [comment]
Hi @qasamppa i would like to find if its resolved and i would love to help you.

**Comment by qasamppa** [comment]
Ok, I executed again, installed plugin from scratch, jira project, project plan id and tagging jira test id, all should be ok. Still I get same info.
Data: { error: 'Error assembling issue data: project is required' }

<img width="1717" alt="Näyttökuva 2023-3-22 kello 8 59 24" src="https://user-images.githubusercontent.com/113007463/226826646-24966acb-7e5d-4eae-8b72-ee31a06b500b.png">

**Comment by inluxc** [comment]
@qasamppa did confirm what @rodrigoodhin said to validate?

**Comment by qasamppa** [comment]
> Hi @qasamppa ,
> I was able to reproduce your problem.
> You are trying to import the result of a test that does not exist in the configured Test Plan.
> Can you please add the Test to the Test Plan, try again and report here if it worked?
> Thanks

Test has been configured to Test Plan for sure. That's not the case.
