### ISSUE TITLE
Server mode requires project even it is in playwright.config.ts

### ISSUE THREAD

**Issue by qasamppa** [inluxc/playwright-xray#48]
**Describe the bug**
playwright-xray plugin requires project in server mode, even project has been configured to playwright.config.ts. This happens in playwright-xray version 0.5.5.

**To Reproduce**
1. Configure server mode
2. Add JIRA ID tag to your test
3. Execute test suite with tag.

**Expected behavior**
Results should be sent to JIRA. New execution should be created with test results under configured test plan.

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS 13.4.1 (c)
 - Browser chromium, firefox and webkit
 - playwright-xray version 0.5.5

**Additional context**
[playwright-xray-error.log](https://github.com/inluxc/playwright-xray/files/12212828/playwright-xray-error.log)
<img width="747" alt="Näyttökuva 2023-7-31 kello 11 05 23" src="https://github.com/inluxc/playwright-xray/assets/113007463/57ca4d1e-0feb-4909-a583-c333164a7aac">
<img width="912" alt="Näyttökuva 2023-7-31 kello 11 14 52" src="https://github.com/inluxc/playwright-xray/assets/113007463/6563f3c3-b228-449c-8606-1633c5c944f5">

**Comment by qasamppa** [comment]
[playwright-xray-error.log](https://github.com/inluxc/playwright-xray/files/12212884/playwright-xray-error.log)

**Comment by inluxc** [comment]
Thanks for the heads up, checking it out.
