### ISSUE TITLE
Flaky tests status handling with Custom Test status

### ISSUE THREAD

**Issue by qasamppa** [inluxc/playwright-xray#49]
**Is your feature request related to a problem? Please describe.**
Flaky test status handling.

**Describe the solution you'd like**
E.g. flaky tests could be reported as custom status set in JIRA Xray. E.g. custom status FAIL-FLAKY configured to JIRA Xray and plugin could set flaky test with custom status.

**Describe alternatives you've considered**

**Additional context**
playwright.config.ts could have status field for flaky tests.

**Comment by inluxc** [comment]
We are analysing this issue

**Comment by Niklas-Back** [comment]
I have implemented the functionality but Im waiting for feedback before commiting
https://github.com/inluxc/playwright-xray/issues/58
