### ISSUE TITLE
playwright-xray in Server mode: Test steps are missing from Test Executions

### ISSUE THREAD

**Issue by qasamppa** [inluxc/playwright-xray#51]
**Describe the bug**
Test Execution does not include any test steps information.

**To Reproduce**
1. Execute test.
2. Check Test Execution details.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1 (c)
 - Browser safari, chrome and Firefox
 - Version 0.5.6

**Additional context**

**Comment by inluxc** [comment]
By test information, what do you mean?
We send the default information from playwright it self.

**Comment by qasamppa** [comment]
I mean test steps like documented in this screenshot.
https://github.com/inluxc/playwright-xray/blob/main/assets/xray-result.png

**Comment by qasamppa** [comment]
Sorry, my bad.

> Notes
> 
> To have the steps imported you have to create then in the test issue itself. The steps will be imported by order of execution and inserted into the test.

And I don't have steps in my example case. If I want them, I should use test.step module in my tests. So this issue can be closed.
