### ISSUE TITLE
can we replace the default summary ? 

### ISSUE THREAD

**Issue by HamzaMiz** [inluxc/playwright-xray#59]
Hello , thank you for the project , it's amazing you saved us alot of time 
I saw that in the project the default summary is   private readonly defaultRunName = `[${new Date().toUTCString()}] - Automated run`;

i add my own summary like this  `[
      'playwright-xray',
      {
        jira: {
          url: 'https://waykonect.atlassian.net',
          type: 'cloud',
          apiVersion: '1.0',
        },
        cloud: {
          client_id: clientId,
          client_secret: clientSecret,
        },
        summary: `[${new Date().toLocaleString('fr-FR', { timeZone: 'Europe/Paris' })}] - Automated `,
        projectKey: projectKey,
        testPlan: testPlan,
        debug: false,
        testEnvironments: process.env.ENV,
      },` but when i test , it always take the default summary name

**Comment by Niklas-Back** [comment]
Added summary option in playwright.config.ts

**Comment by HamzaMiz** [comment]
cool, waiting for the next release ^^ thanks

**Comment by HamzaMiz** [comment]
@Niklas-Back  Hello again is it possible to import Label for test excution also ? 
<img width="1007" alt="Screenshot 2024-03-06 at 11 19 20" src="https://github.com/inluxc/playwright-xray/assets/94066399/cf809586-250b-42d7-98d0-1a3bf7994237">
maybe i can already with the current config but dont know which key point to that

**Comment by NiklasBack** [comment]
As I understand the custom fields are per test case. I have to investigate if it is possible to do it the same way as they do it in the playwright-junit-reporter with e.g. testInfo.annotations.push({ type: 'test_id', description: '1234' });

**Comment by HamzaMiz** [comment]
yes , in fact i m using junit report before using this library

**Comment by NiklasBack** [comment]
Adding it on the same level as info shouldn't be a big issue. I wonder if it should be in the playwright config file or in an external file. What would be more convenient?  E.g. customFields: './myCustomFields.json'

**Comment by HamzaMiz** [comment]
i think in config is more desired , but i can work with json files also , but to be more elegant i think it should something like this `[
      'playwright-xray',
      {
        jira: {
          url: 'https://waykonect.atlassian.net',
          type: 'cloud',
          apiVersion: '1.0',
        },
        cloud: {
          client_id: clientId,
          client_secret: clientSecret,
        },
        summary: `[${new Date().toLocaleString('fr-FR', { timeZone: 'Europe/Paris' })}] - Automated `,
        projectKey: projectKey,
        testPlan: testPlan,
        debug: false,
        testEnvironments: process.env.ENV,
**customFields:[ "Label" : exampleLabel , "priority" : high]**

      },
    ],`

**Comment by HamzaMiz** [comment]
i would like to move this discussion to another request so we can close default summary one since it was done but i dont know how

**Comment by NiklasBack** [comment]
I can try

**Comment by NiklasBack** [comment]
Created new issue "Is it possible to import Label for test execution"
