### ISSUE TITLE
Function to import test cases into Xray and to stamp the code with test(XXX-123 | Testcase...

### ISSUE THREAD

**Issue by Niklas-Back** [inluxc/playwright-xray#64]
The idea is to have a code snippet going through the test cases with e.g. npm run xray-import to import the testcases (with test steps) to Xray and then e.g. npm run xray-tag-tests to tag each test case with the correct test key?

Is anybody working an this? Would it be a nice feature to have?

**Comment by inluxc** [comment]
Do you mean create the test in Playwright and generate the tests and test cases after?

**Comment by NiklasBack** [comment]
Yes, Xray should reflect the test code. Right now the test case importer as I call it, imports the tests and test steps to xray and thereafter renames the test cases with the Xray test case id. My next goal is to update the test cases in xray e.g renamed test cases, test steps, addition and deletion of test steps.
