### ISSUE TITLE
can we add the ability to create the test in jira if the test key was not found 

### ISSUE THREAD

**Issue by HamzaMiz** [inluxc/playwright-xray#65]
contexte : 
<img width="611" alt="Screenshot 2024-04-18 at 13 37 22" src="https://github.com/inluxc/playwright-xray/assets/94066399/d2ef6a31-dc02-4208-9e35-f24fca805e75">
i have some setup tests that they dont have tests on jira 
solution 1 : i would like the  option  if i want to upload the result for certain test or not upload 
solution 2 : if a test dont have a key it will be created automatically in jira and take the description as title ( i dont know the behaviour if there's mandatory fields )

**Comment by Niklas-Back** [comment]
That should be doable but I'm working on an other solution that might do the work. Do you think this would solve the issue? I'm currently implementing synchronization functionality into my xraytestimporter so it will rename test cases and test steps in Xray + add and remove test steps based on the source code. This is based on the issue https://github.com/inluxc/playwright-xray/issues/64

Below are the instructions of how to use it. 
# Xray reporter for Playwright
Imports Playwright test cases to Xray

## Install
npm install playwright-xray-testimporter 

## Usage
Add the `xray.testimporter.config.json` configuration file to the root of your project. 

* `client_id` Mandatory, Xray client id 
* `client_secret` Mandatory, Xray client secret
* `projectKey` Mandatory, Project key to the Jira project
* `xray_test_repository_folder` Optional, Xray folder to place the imported tests into
* `test_input_folder` Mandatory, Relative path to the Playwright tests
* `test_output_folder` Mandatory, Relative path to where the updated Playwright tests should be placed
* `max_test_cases` Optional, defaults to 100. Importing a lot of test cases can take a while, so better do it in batches.

```typescript
{
    "client_id": "",
    "client_secret": "",
    "projectKey": "TES",
    "xray_test_repository_folder": "",
    "test_input_folder": "./test/test_files_write",
    "test_output_folder": "./test/test_files_write",
    "max_test_cases": 100
}
```
To start the import, type the command below in terminal:
npx xraytestimporter
`

## Notes
* If the folder option `xray_test_repository_folder` is used, the folder has to exist
* The `test_output_folder`and `test_input_folder` must exist before running he testimporter

**Comment by HamzaMiz** [comment]
so to understand this clearly you want to create tests on jira based on the source code instead of relying of creating the test itself manually in jira than using the test key ?

**Comment by HamzaMiz** [comment]
for your solution to work the tests needs unique test key that doesnt exist in jira already so u wont remove existing test with the same key . 
and what the second time you want to import , what the expected behaviour ? do u update the tests or remove the test than replace it ?

**Comment by Niklas-Back** [comment]
Yes, that's correct. The code is the source and the test cases are created and modified in Xray reflecting the code. So if a test step is added/ deleted or modified, the corresponding test case in Xray is updated accordingly. If a test case is added in code, a new test case is created in Xray and the code is updated with the key. But if a test case is deleted in code, the corresponding Xray test case wont be deleted.

The idea is that when a new test case is written in code it has to be imported with the command `npx xraytestimporter`. Existing test cases wont be affected. Running the command `npx xraytestimporter --update` will update existing test cases.

Hope it made sense because English is not my native language.

**Comment by HamzaMiz** [comment]
yes i understand , but i think we should use multipart api instead of the normal one , because if there's a required field you cannot import the test , u need to fill that field and only the multipart api can do that

**Comment by HamzaMiz** [comment]
so we need to add jira api fields credentials

**Comment by Niklas-Back** [comment]
Unfortunately yes 😞 The Xray API doesn't support renaming test cases

**Comment by NiklasBack** [comment]
I will close this because it is related to #62
