### ISSUE TITLE
Can i generate  xray report without client_id and client_secret_id ?

### ISSUE THREAD

**Issue by ewadusDev** [inluxc/playwright-xray#67]
I purpose to generate report json file  by no need to set  client_id and client_secret_id for authentication before generate report file.  
I set optional  config debug: true for getting  xray-payload.json and upload it directly to execution issue for now.
I don't want to share client_id and client_secret_id to other people.
Do you have solution for this ? 

Thanks for helping.

**Comment by NiklasBack** [comment]
Hi, what we do is that we use the secret storage in e.g. jenkins to store the client_id and the client_secret and set corresponding environment variables but that doesn't perhaps help if you want to run it locally. You still have to set those variables locally. Currently there is unfortunately no way to bypass the initial authentication to Xray.

**Comment by inluxc** [comment]
Looks like you have your solution.

**Comment by ewadusDev** [comment]
My solution for now is  create a converter playwright report.json to xray report.json instead.

**Comment by NiklasBack** [comment]
I've added a dryRun switch and will soon make a PR. Would  you have time to test it before merge?
