### ISSUE TITLE
Ability to add Custom Fields

### ISSUE THREAD

**Issue by vini46** [inluxc/playwright-xray#71]
*Ability to add Custom Fields**
One of my Jira Project requires "Story Points" and "Acceptance Criteria", due to which I am not able to use this plugin, it throws an error saying "Error creating Test Execution - Issue create failed! - customfield_10115: Story Points is required., customfield_10572: Acceptance Criteria is required."

**Describe the solution you'd like**
We should be taking in custom fields in config which can be then formed as request data to be uploaded to Jira, 

`   customField: {
          customfield_10115: 1,
          customfield_10572: 'This is from test Automation'
        }`

**Comment by NiklasBack** [comment]
I tried to get it to work with the import executions but there seems to be an issue with custom fields. According to Xray importing executions only works with Xray test execution custom fields. Their work around is to import the execution and thereafter use the Jira APIs to update the custom fields (haven't tried it so I don't know if it works) They have registered an issue regarding this https://jira.getxray.app/browse/XRAYCLOUD-6830 (see #62)

**Comment by karljohan122** [comment]
Currently running into the same problem

**Comment by NiklasBack** [comment]
Does it work if the fields are present but not mandatory?

**Comment by karljohan122** [comment]
Making the field optional didn't make a difference iirc. I can try again shortly and let you know.

**Comment by NiklasBack** [comment]
Did you have time to test?

**Comment by NiklasBack** [comment]
Closing this because it's related to #62
