### ISSUE TITLE
Property "testInfo" is required to create a new Test version for Test 

### ISSUE THREAD

**Issue by sn-sstone** [inluxc/playwright-xray#75]
**Describe the bug**
Whenever I try to run the test, I get the following error when the test has the "Test Type" as "Generic" in XRay. As soon as I change it over to manual the error goes away.

**Error**

```
Property "testInfo" is required to create a new Test version for Test SND-4030
```

**XRay Reporteer Config**

```typescript
    'playwright-xray',
    {
      jira: {
        url: process.env.XRAY_URL,
        type: 'cloud',
        apiVersion: '1.0',
      },
      cloud: {
        client_id: process.env.XRAY_CLIENT_ID,
        client_secret: process.env.XRAY_CLIENT_SECRET,
      },
      projectKey: process.env.XRAY_PROJECT_KEY || 'SND',
      testPlan: process.env.XRAY_TEST_PLAN,
      debug: false
    },
  ]);
```

**Expected behavior**
The test results are uploaded to JIRA.

**Screenshots**
**Error in console**
![CleanShot 2024-10-01 at 15 46 49@2x](https://github.com/user-attachments/assets/dfe03baa-9fb3-4f0b-8d30-4b5c88178c0e)

**Test Type Location in XRay**
![CleanShot 2024-10-01 at 16 03 32@2x](https://github.com/user-attachments/assets/ab0eca33-d201-448d-8cb1-1959c6a95a2c)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari

**Comment by NiklasBack** [comment]
Can you set the flag dryRun: true and post the "xray-payload.json" file?

**Comment by sn-sstone** [comment]
`

**Comment by Niklas-Back** [comment]
Interesting, I tried the same on our Jira, and it worked. When you create your test in Jira, are they assigned Generic by default? I have to check with our Jira team what could be the cause.

**Comment by sn-sstone** [comment]
> Interesting, I tried the same on our Jira, and it worked. When you create your test in Jira, are they assigned Generic by default? I have to check with our Jira team what could be the cause.

By default they have the type "Manual".

**Comment by sn-sstone** [comment]
> Do you know how to import xray-payload.json with Curl or Postman? It would be interesting to know if you get the same error.

I just tried and I got the same message.
![CleanShot 2024-10-03 at 10 39 36@2x](https://github.com/user-attachments/assets/3339628a-eb99-40fa-b62f-4113d765d7c5)

**Comment by Niklas-Back** [comment]
As I understand, you run Jira and Xray in the cloud just like us so there shouldn't be any version issues, so I have to contact Xray and ask them what could be the cause why it works for us and not for you. Btw, do you know the reason why the test cases has been changed to generic?

**Comment by NiklasBack** [comment]
Hi, I sent the JSON file to Xray to verify if there are any issues when it comes to importing it to tests, set to "Generic", and according to them it should work. The question is if there is something in your Xray/Jira configuration that hinders you to import?

**Comment by sn-sstone** [comment]
> Hi, I sent the JSON file to Xray to verify if there are any issues when it comes to importing it to tests, set to "Generic", and according to them it should work. The question is if there is something in your Xray/Jira configuration that hinders you to import?

How would I check this?

**Comment by NiklasBack** [comment]
What I did is that I asked our Jira team and they opened a support case with Xray, so Im guessing there is some configuration issue. But I dont know Jira/Xray that well.

**Comment by NiklasBack** [comment]
Sorry closed accidentally

**Comment by sn-sstone** [comment]
> What I did is that I asked our Jira team and they opened a support case with Xray, so Im guessing there is some configuration issue. But I dont know Jira/Xray that well.

OK I'll try to reach out to them sometime this week and update here when I get a response.

**Comment by sn-sstone** [comment]
Just an update - I reached out to them, and they also said it worked for them. However, I'm still in contact with them troubleshooting it on our end.

**Comment by Niklas-Back** [comment]
Hi, what is the status? Have you been able to solve the problem?

**Comment by sn-sstone** [comment]
Just a quick update. I'm still working with XRAY support. They had me try a couple of things but I'm still getting the error.

**Comment by sn-sstone** [comment]
This is what I got from Xray support so far, but I do not understand as the test in question has one version and it is the default. I'm still working with them.

You see the error as you are using Xray Enterprise with [Test Case Versioning](https://docs.getxray.app/display/XRAYCLOUD/Test+Case+Versioning)
To overcome this situation, you may follow any one of the following:
1.  Add a default Test case version - refer to ** [Managing Test Versions](https://docs.getxray.app/display/XRAYCLOUD/Test+Case+Versioning#TestCaseVersioning-ManagingTestVersions)
2. Pass the testinfo object
https://docs.getxray.app/display/XRAYCLOUD/Using+Xray+JSON+format+to+import+execution+results#UsingXrayJSONformattoimportexecutionresults-testinfo
3. If you are not using Xray Enterprise, you may choose to disable it so that you will not see this error.

**Comment by sn-sstone** [comment]
@Niklas-Back I think at this point we can close this out. I have been working with the XRAY team and I think the answer I have gotten from them is to do one of the following.

1. Not use test type "Generic"
2. Turn off Test Case Versioning under Jira Settings > Apps > Test Case Versioning  
3. Send testInfo in your results (Which I think this plugin does not do)
https://docs.getxray.app/display/XRAYCLOUD/Using+Xray+JSON+format+to+import+execution+results#UsingXrayJSONformattoimportexecutionresults-testinfo

**Comment by Niklas-Back** [comment]
Thanks, you are right. I will have a look at the testIfo object to see if I can add it in a future release

**Comment by NiklasBack** [comment]
Thanks, you are right. I will have a look at the testIfo object to see if I can add it in a future release.
