### ISSUE TITLE
Running tests with "dryRun:true" is showing results (Summary) wrong and xray-payload.json incomplete

### ISSUE THREAD

**Issue by jreyes-fy** [inluxc/playwright-xray#77]
I have two tests to run in 3 browsers.
I have the 3 browsers configured in config file.
After executing the command "npx playwright test", I see the output as follows (attached snapshot):

Starting a Dry Run with 6 tests
 
⛔ Chromium | QE-3486 | Test 2
✅ Chromium | QE-3485 | Invalid Credentials Test
✅ Firefox | QE-3485 | Invalid Credentials Test
⛔ Firefox | QE-3486 | Test 2
⛔ Webkit | QE-3486 | Test 2
✅ Webkit | QE-3485 | Invalid Credentials Test
 
-------------------------------------
 
😀 Successfully performed a Dry Run

However, the Summary is wrong as follows:

Test environments: staging
⏺  Browsers:          Chromium, Firefox, Webkit
⏺  Test plan:         QE-3392
⏺  Test Duration:     17s 
⏺  Tests ran:         6 (including reruns)
⏺  Tests passed:      2
⏺  Tests failed:      2
⏺  Flaky tests:       0
⏺  Skipped tests:     0
 
-------------------------------------
 
⏺  Test execution Dry run has been created

The file xray-payload contain 4 tests, 3 passed and 1 failed. 

EXPECTED:
- Summary of Dry Run should have 3 passed, 3 failed
- xray-payload should have 6 tests, 3 passed and 3 failed
- xray-payload should have browsers info that run the test
[xray-payload.json](https://github.com/user-attachments/files/17528402/xray-payload.json)
![102524_dry_run_issue](https://github.com/user-attachments/assets/3bc41136-9a92-4fd2-99ec-e0a7c1311101)

**Desktop (please complete the following information):**
 - OS: iOS (MacBook Air)
 - Running tests in Visual Studio Code Terminal
 - playwright-xray version: ^0.6.5
 - @playwright/test:  ^1.48.1
 - @types/node: ^22.7.9

**Additional context**

**Comment by Niklas-Back** [comment]
Ill have a look at it on Monday

Regards Niklas

**Comment by NiklasBack** [comment]
This one is a bit more complicated, in fact it is three test runs running simultaneously so in fact three test execution files should be created and imported. I will start by looking at the summarisation issue.

**Comment by Niklas-Back** [comment]
Yes that's correct. What is needed is a rework of the reporter so it can handle several browsers running at the same time, will put in on my todo list

**Comment by Niklas-Back** [comment]
Here it is on Google drive
https://drive.google.com/file/d/1T-WE24uS3NdpSFF19CKIoMq6MdKrIfyT/view?usp=sharing
Add the following in package.json and run npm install
"playwright-xray": "file:./playwright-xray-0.6.6.tgz"

**Comment by NiklasBack** [comment]
Closed and Released with:
https://github.com/inluxc/playwright-xray/releases/tag/0.6.6
