### ISSUE TITLE
screenshot and trace.zip file not uploadng to Jira XRay (Cloud)

### ISSUE THREAD

**Issue by jreyes-fy** [inluxc/playwright-xray#78]
Per documentation and samples in this project, I included in the config file "playwright.config.ts" the following lines:
use: {
        screenshot: 'only-on-failure',
        trace: "retain-on-failure"
    },

After running the tests in GitHub Actions, I get the execution test created in XRay with the number of tests. However, the test that failed does not contain the trace.zip file neither the snapshot.
I only contains the message error in Comment column. 

**Desktop (please complete the following information):**
OS: iOS (MacBook Air)
Running tests in Visual Studio Code Terminal
playwright-xray version: ^0.6.5
@playwright/test: ^1.48.1
@types/node: ^22.7.9

**Additional context**

**Comment by Niklas-Back** [comment]
Hi, can you please provide the reporter section for playwright-xray?
Best regards
Niklas
