### ISSUE TITLE
Error message in Comment field in XRay not formatted (XRay Cloud)

### ISSUE THREAD

**Issue by jreyes-fy** [inluxc/playwright-xray#79]
Added the reporter to config file to get results in Jira XRay test execution.
The failed test is a text comparison.

The tests run in Github Actions, test execution is created in XRAy. However, the comment column contains the error message as follows:

[{"message":"Error: \u001b[2mexpect(\u001b[22m\u001b[31mreceived\u001b[39m\u001b[2m).\u001b[22mtoEqual\u001b[2m(\u001b[22m\u001b[32mexpected\u001b[39m\u001b[2m) // deep equality\u001b[22m\n\nExpected: \u001b[32m\"Test\"\u001b[39m\nReceived: \u001b[31m\"Incorrect username or password.\"\u001b[39m","stack":"Error: \u001b[2mexpect(\u001b[22m\u001b[31mreceived\u001b[39m\u001b[2m).\u001b[22mtoEqual\u001b[2m(\u001b[22m\u001b[32mexpected\u001b[39m\u001b[2m) // deep equality\u001b[22m\n\nExpected: \u001b[32m\"Test\"\u001b[39m\nReceived: \u001b[31m\"Incorrect username or password.\"\u001b[39m\n    at /home/runner/work/qa-automation-ui/qa-automation-ui/fitConsole/tests/loginTest.spec.ts:23:26","location":{"file":"/home/runner/work/qa-automation-ui/qa-automation-ui/fitConsole/tests/loginTest.spec.ts","column":26,"line":23},"snippet":"\u001b[0m \u001b[90m 21 |\u001b[39m     \u001b[36mawait\u001b[39m loginPage\u001b[33m.\u001b[39mlogin(username\u001b[33m,\u001b[39m \u001b[32m\"WrgPwd\"\u001b[39m)\u001b[33m;\u001b[39m\n \u001b[90m 22 |\u001b[39m     \u001b[36mconst\u001b[39m errorMessage \u001b[33m=\u001b[39m \u001b[36mawait\u001b[39m loginPage\u001b[33m.\u001b[39mgetErrorMessage()\u001b[33m;\u001b[39m\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 23 |\u001b[39m     expect(errorMessage)\u001b[33m.\u001b[39mtoEqual(\u001b[32m\"Test\"\u001b[39m)\u001b[33m;\u001b[39m\n \u001b[90m    |\u001b[39m                          \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 24 |\u001b[39m   })\u001b[33m;\u001b[39m\n \u001b[90m 25 |\u001b[39m })\u001b[33m;\u001b[39m\n \u001b[90m 26 |\u001b[39m\u001b[0m"}]

**Expected behavior**
Expected: Test
Received: "Incorrect username or password"

**Screenshots**
attached
![10252024_comment_issue](https://github.com/user-attachments/assets/4d5f90b2-e73d-408c-b07d-37486d36dcc6)

**Desktop (please complete the following information):**
OS: iOS (MacBook Air)
Running tests in Visual Studio Code Terminal
playwright-xray version: ^0.6.5
@playwright/test: ^1.48.1
@types/node: ^22.7.9

**Additional context**

**Comment by Niklas-Back** [comment]
Looks like ansi codes are not properly filtered out from comment. Can you please send the report file after  dry run (just run the test in question)

**Comment by NiklasBack** [comment]
I will try to add an ansi filter

**Comment by Niklas-Back** [comment]
I have updated the ansi filtering, but the problem is that when I run it in our pipelines it strips away the ansi characters correctly (with the old and the new filter) so I wonder if I can send you a package to test before releasing?

**Comment by Niklas-Back** [comment]
New try https://drive.google.com/file/d/1hekIBKTYFxIoMZBcGRjPtbnr0v8_Y0HL/view?usp=sharing

**Comment by Niklas-Back** [comment]
Ok, I think I have to get hold of a Mac so I can debug

**Comment by Niklas-Back** [comment]
Hi, do you have time for a debugging session? I didnt manage to reproduce it in Github Actions or on a Mac

**Comment by Niklas-Back** [comment]
Is this still an issue?

**Comment by inluxc** [comment]
@jreyes-fy Can you test with our latest version please, @Niklas-Back added a few ansi code filter.

**Comment by Niklas-Back** [comment]
I think we have to schedule that debug session soon, did you manage to get your Mac up and running?

**Comment by inluxc** [comment]
This is a strange behaviour. Adding a filter is not the correct way to go, We need to try to replicate behaviour.
