### ISSUE TITLE
Attach plan test with test execution

### ISSUE THREAD

**Issue by MaherAccor** [inluxc/playwright-xray#80]
Hello i would like to know how can added test execution to testplan in the end of executions?
It's possible to add this from the configuration file ?

**Comment by Niklas-Back** [comment]
Yes, if you want the reporter to automatically update Xray with the test execution, you specify the test plan in the playwright config file in the reporter section.

**Comment by MaherAccor** [comment]
can you please shows me full exemple how can do that.

**Comment by Niklas-Back** [comment]
Of course. In the example below test plan TCK-87 is used
reporter: [
    [
      'playwright-xray',
      {
        jira: {
          url: 'https://your-jira-url',
          type: 'server',
          apiVersion: '1.0',
        },
        server: {
          token: 'YOUR_SERVER_TOKEN',
        },
        projectKey: 'TCK',
        testPlan: 'TCK-87',
      },
    ],
  ],

**Comment by MaherAccor** [comment]
i'am using jira cloud et not server in variable jira / url i put which url :  
1.https://xray.cloud.getxray.app/api/v2 (url xray)
2. https://-it.atlassian.net/browse (url project)

**Comment by Niklas-Back** [comment]
You dont  have to specify the xray url because it will default to https://xray.cloud.getxray.app/  The setting is used if it differs from default.
E.g. this is my cloud configuration
{
        jira: {
          url: 'https://myCompany.atlassian.net/',
          type: 'cloud',
          apiVersion: '1.0',
        },
        cloud: {
          client_id: 'xxxxxxxxxxx',
          client_secret: 'yyyyyyyyy',
        },

**Comment by MaherAccor** [comment]
Ok thanks , i have a last question , i want to know if i do somthing in the file package.json .this my file
{
  "name": "xrayplay",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
  "test": "playwright test",
  "posttest": "npm test"
},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@playwright/test": "^1.48.2",
    "@types/node": "^22.9.0",
    "playwright-xray": "^0.6.5"
  }
}

**Comment by MaherAccor** [comment]
i have a error > There are no tests with such /^(.+?) \| / key pattern?

**Comment by MaherAccor** [comment]
if you have a full example with playwright in github it will be very easy for me to know how do that .

**Comment by Niklas-Back** [comment]
Hi, if your test cases looks like this: 

issueID | Test Case Name 

Then post your file with test cases so I can have a look. Also how are you running the tests (Linux, Windows, Mac, Jenkins, Locally, GA etc)

**Comment by Niklas-Back** [comment]
If you are interested you could try my beta that imports testcases from playwright, creates Xray testcases and renames the testcases in playwright to issueID | Test Case Name

**Comment by MaherAccor** [comment]
Thank you for your response this is my config :  
package.json : 
{
  "name": "xrayplay",
  "version": "1.0.0",
  "main": "index.js",
  "scripts":{},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@playwright/test": "^1.48.2",
    "@types/node": "^22.9.0",
    "playwright-xray": "^0.6.5",
    "typescript": "5.6.3"
  }
}
ANd this is the config in playwrights.configs.ts  :  
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// import dotenv from 'dotenv';
// import path from 'path';
// dotenv.config({ path: path.resolve(__dirname, '.env') });

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests-examples',
  testMatch: '**/*.ts', 
  timeout:10*1000,
  expect:{
    timeout:3000
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  //retries: process.env.CI ? 2 : 0,
  retries:1,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

**Comment by MaherAccor** [comment]
I think i forgot something in the conf ?

**Comment by MaherAccor** [comment]
if you can share me your conf in the two package.json and playwright.config.ts

**Comment by Niklas-Back** [comment]
Hi,

This is my playwright.config.ts

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['html'], [
    'playwright-xray',
    {
      jira: {
        url: 'https://myCompany.atlassian.net/',
        type: 'cloud',
        apiVersion: '1.0',
      },
      cloud: {
        client_id: 'xxxxxxx',
        client_secret: 'yyyyyyyyyyy',
      },
      projectKey: 'ABC',
      testPlan: 'ABC-10237',
      testEnvironments: ['Desktop Chrome'],
      debug: true,
      uploadScreenShot: true,
      uploadTrace: false,
      stepCategories: ['test.step']
    },
  ]
  ],

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.TEST_ENVIRONMENT ? process.env.TEST_ENVIRONMENT : 'https://www.myCompany.abc',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'retain-on-failure',
    video: 'off',
    screenshot: 'only-on-failure',
    actionTimeout: 10 * 1000,
    navigationTimeout: 30 * 1000,
    testIdAttribute: 'data-test'
  },

  timeout: 5 * 60 * 1000,

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'Desktop Chrome',
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        isMobile: false
      },

    },

    {
      name: 'Mobile Chrome',
      use: {
        ...devices['Samsung Galaxy S20'],
        channel: 'chrome',
        viewport: { width: 360, height: 667 },
        isMobile: true,
      }
    }
  ],

});

**Comment by Niklas-Back** [comment]
Your package.json is fine. This is mine

{
  "name": "skovde",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.45.2",
    "@types/node": "^20.12.7"
  },
  "dependencies": {
    "playwright-xray": "^0.6.5"
  }
}

**Comment by Niklas-Back** [comment]
Does it work now?

**Comment by MaherAccor** [comment]
no does'nt work , i use npx cucumber-js to run then feature file ?

**Comment by MaherAccor** [comment]
my structure project like this 👍 ├── cucumber.js
├── package.json
├── playwright.config.ts
├── tsconfig.json
├── src/
│   ├── test/
│   │   ├── features/
│   │   │   └── login.feature
│   │   ├── steps/
│   │   │   └── loginSteps.ts

**Comment by Niklas-Back** [comment]
I think that's why it doesn't work. As far as I'm aware we haven't run the reporter with cucumber, I have to look into it. Can you please send your feature and step files?

**Comment by MaherAccor** [comment]
yes 
Feature file :
Feature: Login functionality
@DAPP-33194
Scenario: Successful login
  Given I am on the login page

stepsDefinition  : 
import { Before, After, Given, When, Then } from '@cucumber/cucumber';
import { Browser, Page, chromium, firefox, webkit } from 'playwright';

let browser: Browser;
let page: Page;

Before(async function () {
  // Initialiser le navigateur ici en fonction de la variable d'environnement
  const browserName = process.env.BROWSER || 'chromium'; // Par défaut, utiliser Chromium
  if (browserName === 'chromium') {
    browser = await chromium.launch({ headless: false });
  } else if (browserName === 'firefox') {
    browser = await firefox.launch({ headless: false });
  } else if (browserName === 'webkit') {
    browser = await webkit.launch({ headless: false });
  } else {
    throw new Error(`Browser ${browserName} not supported`);
  }

  // Créer une nouvelle page
  page = await browser.newPage();
});

After(async function () {
  // Fermer le navigateur après chaque test
  await browser.close();
});

Given('I am on the login page', async function () {
  await page.goto('https://www.saucedemo.com/');
});

**Comment by MaherAccor** [comment]
cucumber.js

module.exports = {
    default: [
      '--require-module ts-node/register', // Permet de charger TypeScript
      '--require ./src/tests/steps/**/*.ts', // Emplacement des fichiers de step definitions
      './src/tests/features/**/*.feature', // Charge les fichiers de step definitions
      '--format progress-bar',    // Affichage des résultats                  
      '--parallel 4',
      '--format json:results/cucumber-report.json'
    ].join(' '),

  };

**Comment by MaherAccor** [comment]
tsconfig.json 

{
  "compilerOptions": {
    "target": "ESNext",
    "module": "CommonJS",
    "moduleResolution": "node",
    "outDir": "./dist",
    "strict": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
  
  },
  "include": [
    "src/**/*.ts",
    "global.ts"
  ]
}

**Comment by MaherAccor** [comment]
package json : 

{
  "name": "playwright-bdd",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "cucumber-js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@cucumber/cucumber": "^11.1.0",
    "@playwright/test": "^1.48.2",
    "dotenv": "^16.4.5",
    "playwright": "^1.48.2",
    "playwright-xray": "^0.6.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.3"
  },
  "dependencies": {
    "axios": "^1.7.7",
    "form-data": "^4.0.1"
  }
}

**Comment by MaherAccor** [comment]
<img width="312" alt="Capture d’écran 2024-11-19 à 14 57 59" src="https://github.com/user-attachments/assets/48b567e3-62df-4dc4-904d-753924e687a3">

**Comment by MaherAccor** [comment]
have you a news mister?

**Comment by NiklasBack** [comment]
No not yet, havent had time to install Cucumber

**Comment by MaherAccor** [comment]
ok take your time !

**Comment by NiklasBack** [comment]
Im bit confused, running tests with npx cucumber-js will use the cucumber test runner and not the testrunner that comes with Playright (npx playwright test) so the playwright-xray reporter is not used. So I dont understand why you get the "There are no tests with such /^(.+?) | / key pattern" error. Just to make sure I havent misunderstod anything, can you put your project on github/ gogle drive or something similar, so I can download it ang give it a try (please exclude the node_modules directory)

**Comment by inluxc** [comment]
@MaherAccor sorry i have been a bit out, but we do not support cucumber right now.
In only implements XRay Report system.

We need to check how XRay accepts Cucumber report.

**Comment by MaherAccor** [comment]
Hello @inluxc  i had implemented that in maven project in java (you need just a report.json to send in xray) , but with playwright and cucumber i don't find a solution to send report execution to xray ?

**Comment by MaherAccor** [comment]
https://github.com/mdbasheer333/cucumberpwjts .
I have the same structure used in this project , if you can based it and find a solution .

**Comment by MaherAccor** [comment]
good idea , can you please show me what like this batch file ? it will be launched after execution .

**Comment by NiklasBack** [comment]
@inluxc I dont think this issue is relevant to playwright-xray because we use the Playwright test runner, but cucuber-js uses its own testrunner. So what is needed is a cutom formatter for cucumber-js.

**Comment by MaherAccor** [comment]
I resolve a problem to import the result to xray , know i have other problem to link test execution to test plan , i have some problem , i think the problem come from api xray , i try to find a solution for that.

**Comment by NiklasBack** [comment]
Closing this issue because cucumber-js doesn't use the Playwright testrunner, so the playwright-xray reporter is never started.
