### ISSUE TITLE
Sending test results to Jira server fails

### ISSUE THREAD

**Issue by OliverHoenig** [inluxc/playwright-xray#85]
**Describe the bug**
The Xray upload fails when attempting to upload results to a Jira Server instance.
The `playwright-xray-error.log` indicates the URL used for the API request is incorrect:
`rest/raven/1.0/api/import/execution`
According to the [Xray-documentation](https://docs.getxray.app/display/XRAY/Import+Execution+Results+-+REST) it should be: `/rest/raven/1.0/import/execution`

**To Reproduce**
1. Configure the server version by following the instructions in the [README.md ](https://github.com/inluxc/playwright-xray/tree/main?tab=readme-ov-file#server-version)
2. Run the command: `npx playwright test`
3. Observe the error in the logs or output.

**Expected behavior**
The test results should be successfully uploaded to the Jira Server instance without errors.

**Additional context**
- Potential Cause:
  It seems like this line is causing the error:
  https://github.com/inluxc/playwright-xray/blob/d47466ae9dd1f89904fea8eb9b5e2bb011d04aad/src/xray.service.ts#L238
  I think the condition does not group the ternary operator correctly, leading to the wrong URL construction.
 - Proposed Fix
  Adding brackets to clarify the ternary condition should fix it:
  `this.requestUrl = xray + (this.apiVersion !== '1.0' ? 'rest/raven/${this.apiVersion}/api' : 'rest/raven/1.0');`

I look forward hearing from you and being informed if and when a fix can be expected. Thank you in advance for your time and effort!

**Comment by NiklasBack** [comment]
Closed and Released with:
https://github.com/inluxc/playwright-xray/releases/tag/0.6.6
