### ISSUE TITLE
Expose reporter options type

### ISSUE THREAD

**Issue by csvtuda** [inluxc/playwright-xray#86]
**Is your feature request related to a problem? Please describe.**
The reporter does not export its TypeScript type for the reporter configuration. This leads to potential typos not being detected and prevents IntelliSense from providing useful suggestions.

**Describe the solution you'd like**
I would like the reporter to export its options. For example, in [`index.ts`](https://github.com/inluxc/playwright-xray/blob/c2cb9effd7cd8317abda820c2b8ace44c4e1a003/src/index.ts#L214C1-L215C29):

```diff
  export default XrayReporter;
+ export type { XrayOptions };
```

This would then enhance the configuration when used with `as XrayOptions` or `satisfies XrayOptions`:

```ts
// playwright.config.ts

import type { XrayOptions } from 'playwright-xray';

const config: PlaywrightTestConfig = {
  reporter: [
    [
      'playwright-xray',
      {
        jira: {
          url: 'https://your-jira-url',
          type: 'cloud',
          apiVersion: '1.0',
        },
        cloud: {
          client_id: '',
          client_secret: '',
        },
        projectKey: 'JIRA_CODE',
        testPlan: 'JIRA_CODEXXXXX',
        debug: false,
      } satisfies XrayOptions,
    ],
  ],
};
```

**Describe alternatives you've considered**
- Manually creating a TypeScript type based on the documentation. Error-prone and can quickly become outdated if the reporter configuration is updated.
- Using the library without type checking or IntelliSense, which increases the risk of runtime errors due to typos or misconfigurations.

Thank you for considering this improvement!

**Comment by Niklas-Back** [comment]
Thanks, I will add it in next release

**Comment by inluxc** [comment]
Release in: 0.6.7
