### ISSUE TITLE
Optional configuration mandatory in `XrayOptions` type 

### ISSUE THREAD

**Issue by csvtuda** [inluxc/playwright-xray#89]
Hi,

in #86 you exposed the `XrayOptions` to users of the reporter (thanks for that!). But I think there's a small issue with the optional properties.

According to the documentation, `stepCategories` and `summary` are optional settings. But in `XrayOptions`, they are required.

**MRE**

```ts
import {XrayOptions} from "playwright-xray"

const x = {
  jira: {
    url: 'https://hello.atlassian.net/',
    type: 'cloud',
    apiVersion: '1.0',
  },
  cloud: {
    client_id: 'ID',
    client_secret: 'SECRET',
  },
  projectKey: 'DP',
  testPlan: 'DP-71',
  testExecution: 'DP-72',
  debug: false,
} satisfies XrayOptions;
```

![error](https://github.com/user-attachments/assets/e5591789-5f66-4913-955d-24008e934110)

**Expected behaviour**

I guess our expected behaviour would be either to update the documentation or to mark them as optional in the type. 

I hope suggestions are welcome: I assume you've not made them optional because internally, your reporter _always_ has the summary and steps defined. What I've usually done in the past when developing plugins is to split the configuration types into an internal (not exported) and an external (exported to users) version so that internally I can use the required summary without adding `if (config.summary)` unnecessarily.

**Desktop (please complete the following information):**
 - Version 0.6.7

**Comment by NiklasBack** [comment]
Thanks, I´ll have a look
