### ISSUE TITLE
Support data-driven test results upload

### ISSUE THREAD

**Issue by csvtuda** [inluxc/playwright-xray#90]
Hello.

**Is your feature request related to a problem? Please describe.**

I've recently started using this reporter and it's working great for "normal" test cases. However, in my project we're often dealing with data-driven test cases such like this:

```ts
for (const name of ["Bob", "George", "Linda"]) {
  test(`ABC-123 | greet ${name}`, async ({ page }) => {
    await page.goto('https://example.org/');
    const title = page.getByRole('heading');
    await expect(title).toHaveText(`Hello ${name}!`);
  });
}
```

---

A corresponding, [parameterized](https://docs.getxray.app/display/XRAY/Parameterized+Tests) Xray test case would look like this:

![test definition](https://github.com/user-attachments/assets/7d3fe9ba-2d67-4639-9816-f7359766ad06)

Its dataset like this: 

![dataset](https://github.com/user-attachments/assets/89c48995-525b-4599-8ad7-c0fb3e59c964)

And corresponding test executions like this:

![test execution](https://github.com/user-attachments/assets/837f1b57-89e3-48bc-87fd-0f064975f5ce)

---

The reporter currently doesn't support such parameterized/data-driven tests and uploads and instead creates a "normal" result:

![reuslt](https://github.com/user-attachments/assets/c3efc968-495c-4003-acb7-baf87af5f6b0)

Are there plans to support data-driven tests in the future?

**Describe the solution you'd like**
The solution would probably be to fill out the [`iterations`](https://docs.getxray.app/display/XRAY/Import+Execution+Results#ImportExecutionResults-%22iterations%22object-Data-driventestresults) information in the uploaded Xray JSON.

```ts
test: {
  status: 'PASSED',
  testKey: 'ABC-123',
  iterations: [
    { status: 'PASSED', parameters: [ {name: 'name', value: 'Bob'}] },
    { status: 'PASSED', parameters: [ {name: 'name', value: 'George'}] },
    { status: 'PASSED', parameters: [ {name: 'name', value: 'Linda'}] }
  ]
}
```

The challenge will be finding a way to enhance each test with its parameter information. For this, I can think of two approaches:

1. Let users encode the iteration parameters in the title and decode them in your reporter: 
    ```ts
    test(`ABC-123 name=${name} | greet ${name}`, async () => {
      // ...
    });
    ```

3. Let users attach iteration parameter information and retrieve them in your reporter: 
    ```ts
    test(`ABC-123 | greet ${name}`, async ({}, testinfo) => {
      await testinfo.attach('xray-parameters', { body: JSON.stringify({ name: name }, null, 2) });
    });
    ```

**Describe alternatives you've considered**
Maybe there's also a way to provide a fixture that does this automatically? I'm not sure though.

**Desktop (please complete the following information):**
 - Version 0.6.7

**Comment by csvtuda** [comment]
I haven't had the time to discuss this workaround with the project managers yet (syncing steps is easy enough, that's true). I assume that in the long run we will have to work with Xray's iterations in this project, unfortunately. 

But I can also understand if you feel this is too project-specific and do not want to add a one-size-fits-all solution for parameter mapping.

**Comment by NiklasBack** [comment]
It’s an interesting idea, especially when we need to properly handle reruns of tests in Playwright (now they are just flagged as flaky). If we get reruns to work, then I don’t think it will be too difficult to implement iterations.

**Comment by csvtuda** [comment]
Would you be open to pull requests regarding this topic? I'm the maintainer of the [cypress-xray-plugin](https://github.com/Qytera-Gmbh/cypress-xray-plugin), so I somewhat know my way around Xray 😃

**Comment by inluxc** [comment]
We are always open to PR.

**Comment by Niklas-Back** [comment]
Perhaps we should have a look at implementing iterations in this repo, mostly due to the behavior of Playwright retry but it could be used for the issue raised by csvtuda? I think I might have some time available during the holidays.

**Comment by csvtuda** [comment]
I have already implemented a version that works internally. I will create a PR as soon as possible (even just for inspiration), I just need to integrate it into your workflow.

**Comment by inluxc** [comment]
Can you add test to it?
So we can review it

**Comment by csvtuda** [comment]
I will also add tests.
