### ISSUE TITLE
Reporter breaks `npx playwright test --list`

### ISSUE THREAD

**Issue by csvtuda** [inluxc/playwright-xray#91]
**Describe the bug**
When the reporter is configured, I cannot use `npx playwright test --list` anymore:

```console
$ npx playwright test --list
-------------------------------------
 
⏺  Starting the run with 4 tests
 
There are no tests with such /^(.+?) \| / key pattern
```

**To Reproduce**
1. Create a test file containing:

    ```ts
    for (const name of ["Bob", "George", "Linda"]) {
      test(`DP-21 | greet ${name}`, async () => {
        // ...
      });
    }

    test(`DP-25 | something`, async () => {
      // ...
    });
    ```

    (it also happens without the data-driven test)

2. Run `npx playwright test --list`

**Expected behavior**
I'd expect the reporter not to run at all (if possible?):

```console
$ npx playwright test --list
Listing tests:
  [chromium] › example.spec.ts:4:7 › DP-21 | greet Bob
  [chromium] › example.spec.ts:4:7 › DP-21 | greet George
  [chromium] › example.spec.ts:4:7 › DP-21 | greet Linda
  [chromium] › example.spec.ts:9:7 › DP-25 | something
Total: 4 tests in 1 file
```

**Desktop (please complete the following information):**
 - Version 0.6.7

**Comment by NiklasBack** [comment]
Ill check

**Comment by csvtuda** [comment]
> Does it work if you run as below? npx playwright test --reporter=list

Yes, this works.

**Comment by csvtuda** [comment]
Agreed. I also looked into it a bit and there's unfortunately no way to determine in a reporter whether it's been triggered by an actual test run. The [`cliListOnly` flag](https://github.com/microsoft/playwright/blob/9b5f7f77b22858a1db5cbc0efe5c9dc55e7aeb75/packages/playwright/src/common/config.ts#L54) is only accessible in internal Playwright configurations 😞

You may close this issue if you want, the workaround is acceptable for us :+1:
